name: flutter_quran
description: "A Quran Package you can put in your app and it will work without the need for any other resources."
version: 0.0.2
homepage: https://github.com/heshamerfan97/flutter_quran

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6


  # local storage
  shared_preferences: ^2.3.2

  #UI
  fluttertoast: ^8.2.8

  #Tools
  intl: ^0.19.0
  shadcn_flutter: ^0.0.24

# This package supports all platforms listed below.
# But note that it works and fits on mobile size devices
# Additional Screen Sizes will be supported later
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets:
    - lib/assets/
    - lib/assets/fonts/
    - lib/assets/fonts/hafs.ttf
    - lib/assets/jsons/
    - lib/assets/images/
    - lib/assets/images/surah_header.png

  fonts:
    - family: hafs
      fonts:
        - asset: packages/flutter_quran/assets/fonts/hafs.ttf
    - family: GeistSans
      fonts:
        - asset: packages/shadcn_flutter/fonts/Geist-Black.otf
          weight: 800
        - asset: packages/shadcn_flutter/fonts/Geist-Bold.otf
          weight: 700
        - asset: packages/shadcn_flutter/fonts/Geist-Light.otf
          weight: 300
        - asset: packages/shadcn_flutter/fonts/Geist-Medium.otf
          weight: 500
        - asset: packages/shadcn_flutter/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: packages/shadcn_flutter/fonts/Geist-Thin.otf
          weight: 100
        - asset: packages/shadcn_flutter/fonts/Geist-UltraBlack.otf
          weight: 900
        - asset: packages/shadcn_flutter/fonts/Geist-UltraLight.otf
          weight: 200
        - asset: packages/shadcn_flutter/fonts/Geist-Regular.otf
          weight: 400
    - family: RadixIcons
      fonts:
        - asset: packages/shadcn_flutter/icons/RadixIcons.otf
    - family: BootstrapIcons
      fonts:
        - asset: packages/shadcn_flutter/icons/BootstrapIcons.otf

